### ISSUE TITLE
python3 read_file_sdf.py

### ISSUE THREAD

**Issue by Alex-czh** [lianghongzhuo/PointNetGPD#31]
Traceback (most recent call last):
  File "read_file_sdf.py", line 62, in <module>
    generate_obj_from_ply(i+"/google_512k/nontextured.ply")
  File "read_file_sdf.py", line 48, in generate_obj_from_ply
    p = subprocess.Popen(["pcl_ply2obj", base + ".ply", base + ".obj"])
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pcl_ply2obj': 'pcl_ply2obj'

当我运行这个文件时候，显示这个，我不知道如何解决，谢谢。

**Comment by lianghongzhuo** [comment]
Please install `pcl-tools`.
